### ISSUE TITLE
Error "DocumentAlreadyExists: Document with same name SSM-SessionManagerRunShell already exists"

### ISSUE THREAD

**Issue by StephenKing** [gazoakley/terraform-aws-session-manager-settings#1]
It might be my fault, but I do not understand how I can use this module without previously deleting the document `SSM-SessionManagerRunShell`.

If there is a workaround, maybe it is worth mentioning it in the README.

Thanks.

**Comment by nazroll** [comment]
@gazoakley can you look into this please? i faced the same error as well

**Comment by GuenterS** [comment]
I'm interesting as well as I receive the same error.

**Comment by subtubes-io** [comment]
Yeah this does not work. Getting the same error. Have tried different solutions nothing seems to work switching to using a null resource to run a script now. Hoping this gets fixed some day.

**Comment by heydonovan** [comment]
This looks to be an AWS issue, since 2.0 allows for document edits, and it's not supported:

```
Error creating SSM document: InvalidDocumentSchemaVersion: 2.0 is not a valid schema version for Session document type
```
Their documentation doesn't mention Session documents either:

https://docs.aws.amazon.com/systems-manager/latest/userguide/document-schemas-features.html

Edit: Found this: https://github.com/terraform-providers/terraform-provider-aws/issues/7516

**Comment by nazroll** [comment]
@heydonovan if you try and pull the default documents from SSM, some of it is still in schema version 1.0

**Comment by heydonovan** [comment]
> @heydonovan if you try and pull the default documents from SSM, some of it is still in schema version 1.0

Yup! Noticed that as well. Guess AWS hasn't gotten around to updating those? 🤔

**Comment by tdmalone** [comment]
For those who need a workaround for this - if you have already visited the Session Manager settings page in your account then the document appears to be automatically created.

Delete it with:
```
aws ssm delete-document --name SSM-SessionManagerRunShell
```
If it succeeds you should get no response back.

Then `terraform apply` _before_ visiting the Session Manager console again. You should then be good.

**Comment by matty87a** [comment]
it may be easier to just import the existing document into your state to be managed via Terraform from then on:

`terraform import --var-file=path/to/vars.tfvars 'module.session-manager-settings.aws_ssm_document.session_manager_preferences' SSM-SessionManagerRunShell`

**Comment by yashwanth-cp** [comment]
I got different error : │ Error: Error creating SSM association: InvalidDocument: Document type Session is not supported for associations.any solution for this ?
I am using aws_ssm_association resource to associate document to ec2 instances

**Comment by sedatsencan** [comment]
**Error "DocumentAlreadyExists: Document with same name SSM-SessionManagerRunShell already exists"**

For the error; first, send the import command as follows;
`terraform import 'module.session-manager-settings.aws_ssm_document.session_manager_prefs' SSM-SessionManagerRunShell`

then send **`terraform apply`**.
Bingo!

**Comment by sturlabragason-devoteam** [comment]
@sedatsencan This solves it for me as well!

`terraform import 'module.ssm.aws_ssm_document.session_manager_prefs' SSM-SessionManagerRunShell` 
and then 
`terraform apply`.

**Comment by gazoakley** [comment]
The module currently only allows setting the account level defaults, but there's #8 allows creating documents for per session overrides. Still - you should only have 1 Terraform configuration trying to manage the account level defaults and if you've already set it in the console you'll have to do the import that @sedatsencan suggests - there's nothing I can do in this module to work around that.

**Comment by myrondev** [comment]
Hi, when doing
 this `terraform import 'module.ssm.aws_ssm_document.session_manager_prefs' SSM-SessionManagerRunShell` and `terraform apply` the settings page for a session manager is not opening in an AWS console?

**Comment by ajorpheus** [comment]
For future readers, note that the newly announced [Terraform 1.5](https://github.com/hashicorp/terraform/blob/v1.5/CHANGELOG.md) introduces support for `import` blocks, which allows you to do the following instead of depending on manually executing a command on the CLI:

```
import {
  id = "SSM-SessionManagerRunShell"
  to = module.ssm.aws_ssm_document.session_manager_prefs
}
```
